"""empty message

Revision ID: 0c1a4cec0446
Revises: 46ed6b5cf8db
Create Date: 2023-10-20 21:31:49.973060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1a4cec0446'
down_revision = '46ed6b5cf8db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthdate', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('hobbies', sa.String(length=250), nullable=False))
        batch_op.create_unique_constraint(None, ['hobbies'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('hobbies')
        batch_op.drop_column('birthdate')

    # ### end Alembic commands ###
