"""empty message

Revision ID: d43477dfd9a7
Revises: 0c1a4cec0446
Create Date: 2023-10-20 21:55:30.356019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd43477dfd9a7'
down_revision = '0c1a4cec0446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_hobbies_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_hobbies_key', ['hobbies'])

    # ### end Alembic commands ###
